# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm i
    - run: npm run ci
    - run: npm test
    - name: Upload coverage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: code_coverage
        path: ./coverage
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
